version: '2'
services:
    unno_tracking:
        environment:
            CUDA_VISIBLE_DEVICES: 0
        build:
            context: .
        volumes:
            - ./data:/data/
        ports:
            - "8899:8899"
