version: '2'
services:
    unno-tracking:
        image: skyuuka/unno-tracking
        environment:
            CUDA_VISIBLE_DEVICES: 0
        build:
            context: .
        volumes:
            # host_path: contain_path
            - /tmp/unno_database:/data/
        ports:
            - "8899:8899"
