apiVersion:  apps/v1
kind: Deployment
metadata:
    name: unno-tracking
spec:
    selector: 
        matchLabels: 
            app: unno-tracking
    replicas: 1
    template:
        metadata:
            labels:
                app: unno-tracking
        spec:
            restartPolicy: Always
            containers:
            - name: unno-tracking
              image: skyuuka/unno-tracking
              imagePullPolicy: IfNotPresent
              resources:
                  limits:
                      nvidia.com/gpu: 1
              ports:
              - containerPort: 30164
                protocol: TCP 
              volumeMounts:
              - mountPath: /data
                name: data
            volumes:
            - name: data
              hostPath:
                  path: /tmp/data
                  type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata: 
    name: unno-tracking-service
spec:
    # Expose the service on a static port on each node
    # so that we can access the service from ***outside*** the cluster 
    type: NodePort
    # When the node receives a request on the static port (30163)
    # "select pods with the label 'app' set to 'unno-tracking'"
    # and forward the request to one of them
    selector: 
        app: unno-tracking
    ports:
        # Three types of ports for a service
        # nodePort - a static port assigned on each node
        # port - port exposed internally in the cluster
        # targetPort - the container port to send requests to
        - nodePort: 30164
          port: 8899
          targetPort: 30164
