awscli==1.16.293
boto3==1.10.29
botocore==1.13.29
chardet==3.0.4
click==7.0
colorama==0.4.1
cycler==0.10.0
docutils==0.15.2
flask==1.1.1
flask-cors==3.0.8
flask-minio==0.1.2
idna==2.8
itsdangerous==1.1.0
jmespath==0.9.4
kiwisolver==1.1.0
matplotlib==3.1.2
minio==5.0.5
mysql-connector-python==8.0.18
numpy==1.17.4
opencv-python==4.1.2.30
pillow==6.2.1
pip==19.3.1
protobuf==3.11.0
pyasn1==0.4.8
pyparsing==2.4.5
pytz==2019.3
pyyaml==5.1.2
pyzmq==18.1.1
requests==2.22.0
rsa==3.4.2
s3transfer==0.2.1
tensorboardx==1.9
torch==0.4.1.post2
torchvision==0.2.2.post3
tqdm==4.40.0
urllib3==1.25.7
werkzeug==0.16.0
yacs==0.1.6
